### ISSUE TITLE
CSS reset and CSS base

### ISSUE THREAD

**Issue by yoowinsu** [yoowinsu/blog#30]
```css
/*CSS reset*/
blockquote,body,button,dd,dl,dt,fieldset,form,h1,h2,h3,h4,h5,h6,hr,input,legend,li,ol,p,pre,td,textarea,th,ul{
  margin:0;padding:0
}
body,button,input,select,textarea{
  font:12px/1.5 tahoma,arial,'Hiragino Sans GB','\5b8b\4f53',sans-serif
}
h1,h2,h3,h4,h5,h6{
  font-size:100%
}
address,cite,dfn,em,var{
  font-style:normal
}
code,kbd,pre,samp{
  font-family:courier new,courier,monospace
}
small{
  font-size:12px
}
ol,ul{
  list-style:none
}
a{
  text-decoration:none
}
a:hover{
  text-decoration:underline
}
sup{
  vertical-align:text-top
}
sub{
  vertical-align:text-bottom
}
legend{
  color:#000
}
fieldset,img{
  border:0
}
button,input,select,textarea{
  font-size:100%
}
table{
  border-collapse:collapse;border-spacing:0
}

/*CSS base*/
*,::before,::after{
  box-sizing: border-box
}
.clearfix:after{
  content: '';
  display: block;
  clear: both;
}
```
