### ISSUE TITLE
IOS中input框无法输入的问题以及解决方法

### ISSUE THREAD

**Issue by yoowinsu** [yoowinsu/blog#80]
## 问题
本来项目已测试完毕，但是又发现input框在ios下存在无法输入的问题，一次只能输入一个非中文字符，且无法获取光标，排查了许久，一直没找到原因。在安卓端没有此问题。
后来google了这个问题，发现有其他人也碰到了问题，是因为input元素加了禁止选中的属性`user-select: none;`，导致input无法选中，无法输入的问题。
我突然想起了，项目测试完以后，突然发现很多按钮可以复制选中文字，用户体验不好，所以在该页面用通配符加了`user-select: none;`的属性，也就导致了这个问题。

## 解决方法
如果input被加了这个属性，一般是因为用了通配符，所以可以用`&:not(input)`的选择器给元素加`user-select: none;`的属性就可以啦。
如下：
```css
element:not(input) {
  user-select: none;
}
```
